# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token', models.TextField(max_length=22, primary_key=True, serialize=False, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
