# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_upload', '0003_auto_20160324_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='convoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.picture')),
            ],
        ),
    ]
