# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20160324_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='geoX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='geoY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='highColor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='highX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='highY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='lowColor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='vr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.picture'),
        ),
    ]
