# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pictures/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
