# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.CharField(default='Test', max_length=255),
        ),
    ]
