# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_auto_20160427_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='geoX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='geoY',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='highX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='highY',
            field=models.FloatField(default=0),
        ),
    ]
